vich_uploader:
    db_driver: orm

    mappings:
        logos:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        projects:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        projects_logos:
            uri_prefix: /images/projects/logos
            upload_destination: '%kernel.project_dir%/public/images/projects/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer